[project]
name = "file-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "briefcase>=0.3.26",
    "pyinstaller>=6.19.0",
    "textual>=8.0.0",
]
